// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBod6wTDeWNElQ34rC-8kAEBykw0G825A4',
    appId: '1:369370777956:web:4ddf6bd42a126065bad271',
    messagingSenderId: '369370777956',
    projectId: 'taskapp-e3919',
    authDomain: 'taskapp-e3919.firebaseapp.com',
    storageBucket: 'taskapp-e3919.firebasestorage.app',
    measurementId: 'G-JHFZCET3N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5f_ThLrm3gpx_eRSDBxjhHeJyXK5zNpM',
    appId: '1:369370777956:android:f5c4ed7af40a992abad271',
    messagingSenderId: '369370777956',
    projectId: 'taskapp-e3919',
    storageBucket: 'taskapp-e3919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRIygEXVbi3b1qbOtdPHdPldDtnZHJjq4',
    appId: '1:369370777956:ios:f75e55301bf2c43cbad271',
    messagingSenderId: '369370777956',
    projectId: 'taskapp-e3919',
    storageBucket: 'taskapp-e3919.firebasestorage.app',
    iosBundleId: 'com.example.markazElamal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRIygEXVbi3b1qbOtdPHdPldDtnZHJjq4',
    appId: '1:369370777956:ios:f75e55301bf2c43cbad271',
    messagingSenderId: '369370777956',
    projectId: 'taskapp-e3919',
    storageBucket: 'taskapp-e3919.firebasestorage.app',
    iosBundleId: 'com.example.markazElamal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBod6wTDeWNElQ34rC-8kAEBykw0G825A4',
    appId: '1:369370777956:web:7eb1fd1471aff6e5bad271',
    messagingSenderId: '369370777956',
    projectId: 'taskapp-e3919',
    authDomain: 'taskapp-e3919.firebaseapp.com',
    storageBucket: 'taskapp-e3919.firebasestorage.app',
    measurementId: 'G-JRT324CEWH',
  );
}
